(in-package #:cl-fu)
;;==============================================================================
;; (ql:quickload :cl-fu)(in-package :fu)

(defun refresh ()
  (declare (optimize (speed 3) (space 3) (debug 0)))
   (&refresh))
(defun test ()
 
  (initscr)
  (printw "hello")
  (refresh)
  (getch)
  (endwin))

(defun t1 ()
  (initscr)
  (raw)
  (cbreak )
  (keypad *stdscr* 1)
  (noecho)
  ;;(&nodelay )
  (printw "Type any character and see it in bold\\n")
  (let ((ch (&getch)))
    (print ch)
    (printw "You are-%d--" :int ch)
    (refresh)
    (getch)
    (endwin)
    ch)
)

(defun in ()
  (initscr)
  (raw)
  (cbreak )
  (keypad *stdscr* 1)
  (noecho)
  (refresh)
  )

(defun out ()
  (endwin)
  )

(defun t2 ()
  (printw "Fuck You, Sir!")
  (move 0 0)
  (refresh)
)
